name: graphtagger-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.12
  - bioconda::minimap2
  #- nanoporetech::minimap2 # For apple silicon build
  - bioconda::mosdepth
  - pip
  - pip:
      #- Ruff
      #- black
      - Biopython
      - setuptools_scm
      - build
      - twine
