name: graphtagger
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::minimap2
  - bioconda::mosdepth
  - pip
  - python >=3.12
  - pip:
      - Biopython
      - hatch
      - pytest
      - Ruff
